
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gigabank
    username: ${USER_DB}
    password: ${PASS_DB}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        format_sql: true
        show_sql: false
        use_sql_comments: true
        jdbc:
          lob:
            non-contextual_creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher